#While some like the new models, you may not. Here's your chance to opt-out (Requires restart)
useNewModels = true
#Enable/disable the gooey inventory
useGooeyInventory = true
#Enable/disable the gooey hearts
useGoopyHearts = true
#Caching generated latex covering textures will decrease load time, but will disable recreating the cache if you change resource packs. This cache is stored on your disk. It's recommended to enable this while loading large modpacks
cacheGeneratedTextures = true
#While generating textures, the generator will store all used block textures in memory until all textures are generated. It's recommended to disable this while loading large modpacks
memCacheBaseImages = false
#Large modpacks will eat up all your memory if unique textures are generated for every block, this will apply a generic texture for all cube like models
generateUniqueTexturesForAllBlocks = false
#Got a lot of mods? Unique model generation will be limited to minecraft and changed
fastAndCheapLatexBlocks = true

