
[common_server]
	#Only considered if terrablender installed. Heigher values increase Werewolf region weight (likelyhood to appear)
	#Range: 1 ~ 1000
	werewolfHeavenWeightTerrablender = 2
	#Disable werewolf heaven generation
	disableWerewolfHeaven = false
	#Disable the ore generation
	disableOreGen = false

